import type { AgentRole, TaskStatus } from '@/types';

export const AGENT_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  COMMANDER:          { bg: 'bg-purple-50 dark:bg-purple-950/40',   border: 'border-purple-400',  text: 'text-purple-700 dark:text-purple-300' },
  PLANNER:            { bg: 'bg-blue-50 dark:bg-blue-950/40',       border: 'border-blue-400',    text: 'text-blue-700 dark:text-blue-300' },
  ROUTER:             { bg: 'bg-cyan-50 dark:bg-cyan-950/40',       border: 'border-cyan-400',    text: 'text-cyan-700 dark:text-cyan-300' },
  VERIFIER:           { bg: 'bg-emerald-50 dark:bg-emerald-950/40', border: 'border-emerald-400', text: 'text-emerald-700 dark:text-emerald-300' },
  GUARDRAIL:          { bg: 'bg-amber-50 dark:bg-amber-950/40',     border: 'border-amber-400',   text: 'text-amber-700 dark:text-amber-300' },
  APPROVAL:           { bg: 'bg-amber-50 dark:bg-amber-950/40',     border: 'border-amber-400',   text: 'text-amber-700 dark:text-amber-300' },
  WORKER_EMAIL:       { bg: 'bg-pink-50 dark:bg-pink-950/40',       border: 'border-pink-400',    text: 'text-pink-700 dark:text-pink-300' },
  WORKER_CALENDAR:    { bg: 'bg-rose-50 dark:bg-rose-950/40',       border: 'border-rose-400',    text: 'text-rose-700 dark:text-rose-300' },
  WORKER_CRM:         { bg: 'bg-orange-50 dark:bg-orange-950/40',   border: 'border-orange-400',  text: 'text-orange-700 dark:text-orange-300' },
  WORKER_DOCUMENT:    { bg: 'bg-indigo-50 dark:bg-indigo-950/40',   border: 'border-indigo-400',  text: 'text-indigo-700 dark:text-indigo-300' },
  WORKER_SPREADSHEET: { bg: 'bg-teal-50 dark:bg-teal-950/40',       border: 'border-teal-400',    text: 'text-teal-700 dark:text-teal-300' },
  WORKER_BROWSER:     { bg: 'bg-sky-50 dark:bg-sky-950/40',         border: 'border-sky-400',     text: 'text-sky-700 dark:text-sky-300' },
  WORKER_RESEARCH:    { bg: 'bg-violet-50 dark:bg-violet-950/40',   border: 'border-violet-400',  text: 'text-violet-700 dark:text-violet-300' },
  WORKER_KNOWLEDGE:   { bg: 'bg-emerald-50 dark:bg-emerald-950/40', border: 'border-emerald-400', text: 'text-emerald-700 dark:text-emerald-300' },
  WORKER_SUPPORT:     { bg: 'bg-lime-50 dark:bg-lime-950/40',       border: 'border-lime-400',    text: 'text-lime-700 dark:text-lime-300' },
  WORKER_OPS:         { bg: 'bg-gray-50 dark:bg-gray-950/40',       border: 'border-gray-400',    text: 'text-gray-700 dark:text-gray-300' },
  WORKER_VOICE:       { bg: 'bg-fuchsia-50 dark:bg-fuchsia-950/40', border: 'border-fuchsia-400', text: 'text-fuchsia-700 dark:text-fuchsia-300' },
  WORKER_CODER:       { bg: 'bg-green-50 dark:bg-green-950/40',     border: 'border-green-400',   text: 'text-green-700 dark:text-green-300' },
  WORKER_DESIGNER:    { bg: 'bg-pink-50 dark:bg-pink-950/40',       border: 'border-pink-300',    text: 'text-pink-700 dark:text-pink-300' },
  WORKER_STRATEGIST:  { bg: 'bg-slate-50 dark:bg-slate-950/40',     border: 'border-slate-400',   text: 'text-slate-700 dark:text-slate-300' },
  WORKER_MARKETING:   { bg: 'bg-red-50 dark:bg-red-950/40',         border: 'border-red-400',     text: 'text-red-700 dark:text-red-300' },
  WORKER_TECHNICAL:   { bg: 'bg-cyan-50 dark:bg-cyan-950/40',       border: 'border-cyan-300',    text: 'text-cyan-700 dark:text-cyan-300' },
  WORKER_FINANCE:     { bg: 'bg-yellow-50 dark:bg-yellow-950/40',   border: 'border-yellow-400',  text: 'text-yellow-700 dark:text-yellow-300' },
  WORKER_HR:          { bg: 'bg-amber-50 dark:bg-amber-950/40',     border: 'border-amber-300',   text: 'text-amber-700 dark:text-amber-300' },
  WORKER_GROWTH:      { bg: 'bg-orange-50 dark:bg-orange-950/40',   border: 'border-orange-300',  text: 'text-orange-700 dark:text-orange-300' },
  WORKER_CONTENT:     { bg: 'bg-pink-50 dark:bg-pink-950/40',       border: 'border-pink-400',    text: 'text-pink-700 dark:text-pink-300' },
  WORKER_SEO:         { bg: 'bg-emerald-50 dark:bg-emerald-950/40', border: 'border-emerald-300', text: 'text-emerald-700 dark:text-emerald-300' },
  WORKER_PR:          { bg: 'bg-blue-50 dark:bg-blue-950/40',       border: 'border-blue-300',    text: 'text-blue-700 dark:text-blue-300' },
  WORKER_LEGAL:       { bg: 'bg-slate-50 dark:bg-slate-950/40',     border: 'border-slate-400',   text: 'text-slate-700 dark:text-slate-300' },
  WORKER_SUCCESS:     { bg: 'bg-teal-50 dark:bg-teal-950/40',       border: 'border-teal-300',    text: 'text-teal-700 dark:text-teal-300' },
  WORKER_ANALYTICS:   { bg: 'bg-indigo-50 dark:bg-indigo-950/40',   border: 'border-indigo-300',  text: 'text-indigo-700 dark:text-indigo-300' },
  WORKER_PRODUCT:     { bg: 'bg-violet-50 dark:bg-violet-950/40',   border: 'border-violet-300',  text: 'text-violet-700 dark:text-violet-300' },
  WORKER_PROJECT:     { bg: 'bg-sky-50 dark:bg-sky-950/40',         border: 'border-sky-300',     text: 'text-sky-700 dark:text-sky-300' },
};

export const DEFAULT_COLOR = { bg: 'bg-slate-50 dark:bg-slate-950/40', border: 'border-slate-400', text: 'text-slate-700 dark:text-slate-300' };

export const STATUS_COLORS: Record<TaskStatus, string> = {
  PENDING:           'text-muted-foreground',
  IN_PROGRESS:       'text-blue-600 dark:text-blue-400',
  COMPLETED:         'text-green-600 dark:text-green-400',
  FAILED:            'text-red-600 dark:text-red-400',
  SKIPPED:           'text-gray-400',
  AWAITING_APPROVAL: 'text-amber-600 dark:text-amber-400',
};

export const ROLE_EMOJIS: Record<string, string> = {
  COMMANDER:          '🎯',
  PLANNER:            '📋',
  ROUTER:             '🔀',
  VERIFIER:           '✅',
  GUARDRAIL:          '🛡️',
  APPROVAL:           '⚠️',
  WORKER_EMAIL:       '📧',
  WORKER_CALENDAR:    '📅',
  WORKER_CRM:         '👤',
  WORKER_DOCUMENT:    '📄',
  WORKER_SPREADSHEET: '📊',
  WORKER_BROWSER:     '🌐',
  WORKER_RESEARCH:    '🔍',
  WORKER_KNOWLEDGE:   '🧠',
  WORKER_SUPPORT:     '🎧',
  WORKER_OPS:         '⚙️',
  WORKER_VOICE:       '🎤',
  WORKER_CODER:       '💻',
  WORKER_DESIGNER:    '🎨',
  WORKER_STRATEGIST:  '🎯',
  WORKER_MARKETING:   '📣',
  WORKER_TECHNICAL:   '🏗️',
  WORKER_FINANCE:     '💰',
  WORKER_HR:          '👔',
  WORKER_GROWTH:      '🚀',
  WORKER_CONTENT:     '✏️',
  WORKER_SEO:         '📈',
  WORKER_PR:          '📰',
  WORKER_LEGAL:       '⚖️',
  WORKER_SUCCESS:     '🤝',
  WORKER_ANALYTICS:   '📉',
  WORKER_PRODUCT:     '🗺️',
  WORKER_PROJECT:     '📌',
};
