import { AgentRole } from '../types/agent.js';

export const AGENT_ROLE_DISPLAY_NAMES: Record<AgentRole, string> = {
  [AgentRole.COMMANDER]: 'Commander',
  [AgentRole.PLANNER]: 'Planner',
  [AgentRole.ROUTER]: 'Router',
  [AgentRole.VERIFIER]: 'Verifier',
  [AgentRole.GUARDRAIL]: 'Guardrail',
  [AgentRole.APPROVAL]: 'Approval Manager',
  [AgentRole.WORKER_EMAIL]: 'Email Worker',
  [AgentRole.WORKER_CALENDAR]: 'Calendar Worker',
  [AgentRole.WORKER_CRM]: 'CRM Worker',
  [AgentRole.WORKER_DOCUMENT]: 'Document Worker',
  [AgentRole.WORKER_SPREADSHEET]: 'Spreadsheet Worker',
  [AgentRole.WORKER_BROWSER]: 'Browser Automation Worker',
  [AgentRole.WORKER_RESEARCH]: 'Research Worker',
  [AgentRole.WORKER_KNOWLEDGE]: 'Knowledge Worker',
  [AgentRole.WORKER_SUPPORT]: 'Customer Support Worker',
  [AgentRole.WORKER_OPS]: 'Operations Worker',
  [AgentRole.WORKER_VOICE]: 'Voice Worker',
  [AgentRole.WORKER_CODER]: 'Software Engineer',
  [AgentRole.WORKER_DESIGNER]: 'Designer',
  [AgentRole.WORKER_STRATEGIST]: 'Chief Strategist (CEO)',
  [AgentRole.WORKER_MARKETING]: 'Marketing Lead (CMO)',
  [AgentRole.WORKER_TECHNICAL]: 'Technical Architect (CTO)',
  [AgentRole.WORKER_FINANCE]: 'Finance Analyst (CFO)',
  [AgentRole.WORKER_HR]: 'HR & People Ops',
  [AgentRole.WORKER_GROWTH]: 'Growth Engine',
  [AgentRole.WORKER_CONTENT]: 'Content Writer',
  [AgentRole.WORKER_SEO]: 'SEO Specialist',
  [AgentRole.WORKER_PR]: 'Public Relations',
  [AgentRole.WORKER_LEGAL]: 'Legal Advisor',
  [AgentRole.WORKER_SUCCESS]: 'Customer Success',
  [AgentRole.WORKER_ANALYTICS]: 'Analytics Analyst',
  [AgentRole.WORKER_PRODUCT]: 'Product Manager',
  [AgentRole.WORKER_PROJECT]: 'Project Manager',
  // Vibe Coding agents
  [AgentRole.WORKER_APP_ARCHITECT]: 'App Architect',
  [AgentRole.WORKER_APP_GENERATOR]: 'App Code Generator',
  [AgentRole.WORKER_APP_DEBUGGER]: 'App Debugger',
  [AgentRole.WORKER_APP_DEPLOYER]: 'App Deployer',
  [AgentRole.WORKER_SCREENSHOT_TO_CODE]: 'Screenshot to Code',
};

export const WORKER_AGENT_ROLES: AgentRole[] = [
  AgentRole.WORKER_EMAIL,
  AgentRole.WORKER_CALENDAR,
  AgentRole.WORKER_CRM,
  AgentRole.WORKER_DOCUMENT,
  AgentRole.WORKER_SPREADSHEET,
  AgentRole.WORKER_BROWSER,
  AgentRole.WORKER_RESEARCH,
  AgentRole.WORKER_KNOWLEDGE,
  AgentRole.WORKER_SUPPORT,
  AgentRole.WORKER_OPS,
  AgentRole.WORKER_VOICE,
  AgentRole.WORKER_CODER,
  AgentRole.WORKER_DESIGNER,
  AgentRole.WORKER_STRATEGIST,
  AgentRole.WORKER_MARKETING,
  AgentRole.WORKER_TECHNICAL,
  AgentRole.WORKER_FINANCE,
  AgentRole.WORKER_HR,
  AgentRole.WORKER_GROWTH,
  AgentRole.WORKER_CONTENT,
  AgentRole.WORKER_SEO,
  AgentRole.WORKER_PR,
  AgentRole.WORKER_LEGAL,
  AgentRole.WORKER_SUCCESS,
  AgentRole.WORKER_ANALYTICS,
  AgentRole.WORKER_PRODUCT,
  AgentRole.WORKER_PROJECT,
  // Vibe Coding agents
  AgentRole.WORKER_APP_ARCHITECT,
  AgentRole.WORKER_APP_GENERATOR,
  AgentRole.WORKER_APP_DEBUGGER,
  AgentRole.WORKER_APP_DEPLOYER,
  AgentRole.WORKER_SCREENSHOT_TO_CODE,
];

export const ORCHESTRATOR_ROLES: AgentRole[] = [
  AgentRole.COMMANDER,
  AgentRole.PLANNER,
  AgentRole.ROUTER,
  AgentRole.VERIFIER,
  AgentRole.GUARDRAIL,
  AgentRole.APPROVAL,
];
