import { Industry } from '../types/industry.js';

export const INDUSTRY_DISPLAY_NAMES: Record<Industry, string> = {
  [Industry.HEALTHCARE]: 'Healthcare',
  [Industry.EDUCATION]: 'Education',
  [Industry.RETAIL]: 'Retail',
  [Industry.LOGISTICS]: 'Logistics & Supply Chain',
  [Industry.FINANCE]: 'Finance & Banking',
  [Industry.INSURANCE]: 'Insurance',
  [Industry.RECRUITING]: 'Recruiting & HR',
  [Industry.LEGAL]: 'Legal',
  [Industry.HOSPITALITY]: 'Hospitality & Travel',
  [Industry.CUSTOMER_SUPPORT]: 'Customer Support',
  [Industry.MANUFACTURING]: 'Manufacturing',
  [Industry.CONSULTING]: 'Consulting',
  [Industry.GENERAL]: 'General',
};

export const INDUSTRY_KEYWORDS: Record<Industry, string[]> = {
  [Industry.HEALTHCARE]: [
    'patient',
    'clinic',
    'medical',
    'intake',
    'claims',
    'ehr',
    'doctor',
    'hospital',
    'prescription',
    'diagnosis',
    'appointment',
    'hipaa',
    'lab',
    'nurse',
    'pharmacy',
    'insurance',
    'health',
    'discharge',
    'referral',
  ],
  [Industry.EDUCATION]: [
    'student',
    'course',
    'enrollment',
    'syllabus',
    'grade',
    'university',
    'school',
    'teacher',
    'curriculum',
    'assignment',
    'exam',
    'lms',
    'lecture',
    'tuition',
    'transcript',
    'campus',
    'faculty',
  ],
  [Industry.RETAIL]: [
    'order',
    'product',
    'inventory',
    'sku',
    'cart',
    'checkout',
    'shipment',
    'return',
    'refund',
    'store',
    'purchase',
    'discount',
    'catalog',
    'ecommerce',
    'warehouse',
    'supplier',
  ],
  [Industry.LOGISTICS]: [
    'shipment',
    'freight',
    'carrier',
    'tracking',
    'warehouse',
    'dispatch',
    'route',
    'delivery',
    'manifest',
    'pallet',
    'load',
    'logistics',
    'fleet',
    'driver',
    'customs',
    'inventory',
  ],
  [Industry.FINANCE]: [
    'transaction',
    'account',
    'ledger',
    'invoice',
    'payment',
    'bank',
    'audit',
    'reconciliation',
    'budget',
    'financial',
    'balance',
    'statement',
    'tax',
    'compliance',
    'portfolio',
    'trade',
  ],
  [Industry.INSURANCE]: [
    'policy',
    'claim',
    'premium',
    'adjuster',
    'underwriter',
    'beneficiary',
    'coverage',
    'deductible',
    'renewal',
    'actuarial',
    'insured',
    'broker',
    'endorsement',
    'risk',
    'liability',
  ],
  [Industry.RECRUITING]: [
    'candidate',
    'resume',
    'job',
    'interview',
    'offer',
    'onboarding',
    'recruiter',
    'applicant',
    'hire',
    'position',
    'ats',
    'headcount',
    'workforce',
    'screening',
    'background check',
  ],
  [Industry.LEGAL]: [
    'contract',
    'clause',
    'litigation',
    'counsel',
    'brief',
    'deposition',
    'discovery',
    'compliance',
    'regulatory',
    'statute',
    'attorney',
    'court',
    'precedent',
    'draft',
    'review',
    'nda',
  ],
  [Industry.HOSPITALITY]: [
    'reservation',
    'booking',
    'hotel',
    'guest',
    'check-in',
    'check-out',
    'room',
    'amenity',
    'travel',
    'itinerary',
    'concierge',
    'housekeeping',
    'restaurant',
    'event',
    'venue',
  ],
  [Industry.CUSTOMER_SUPPORT]: [
    'ticket',
    'support',
    'complaint',
    'resolution',
    'escalation',
    'sla',
    'helpdesk',
    'customer',
    'satisfaction',
    'refund',
    'feedback',
    'nps',
    'agent',
    'queue',
    'response time',
  ],
  [Industry.MANUFACTURING]: [
    'production',
    'assembly',
    'bom',
    'quality control',
    'defect',
    'maintenance',
    'downtime',
    'shift',
    'plant',
    'equipment',
    'supplier',
    'procurement',
    'iso',
    'six sigma',
    'lean',
  ],
  [Industry.CONSULTING]: [
    'engagement',
    'deliverable',
    'stakeholder',
    'strategy',
    'roadmap',
    'framework',
    'assessment',
    'recommendation',
    'deck',
    'proposal',
    'sow',
    'retainer',
    'milestone',
    'analysis',
  ],
  [Industry.GENERAL]: [
    'task',
    'workflow',
    'process',
    'automate',
    'schedule',
    'report',
    'data',
    'notification',
    'email',
    'document',
    'calendar',
    'meeting',
    'reminder',
    'summary',
  ],
};
