/**
 * PII redaction in export converters.
 *
 * Verifies the redaction pipeline that runs BEFORE the converter is
 * invoked. The export.service.ts `applyRedactionIfApplicable` method
 * is the surface; we exercise the underlying detectPII contract +
 * the document-payload transformation.
 */
import { describe, it, expect } from 'vitest';
import { detectPII, PIIType } from '../../packages/security/src/index.js';
import { exportPdf, exportJson } from '../../apps/api/src/services/exporters/index.js';

describe('detectPII (used by redact pipeline)', () => {
  it('detects email addresses', () => {
    const result = detectPII('Contact me at jane.doe@example.com or admin@foo.bar');
    expect(result.containsPII).toBe(true);
    expect(result.found).toContain(PIIType.EMAIL);
    expect(result.redacted).toContain('[REDACTED-EMAIL]');
    expect(result.redacted).not.toContain('jane.doe@example.com');
  });

  it('detects SSNs in standard format', () => {
    const result = detectPII('SSN: 123-45-6789');
    expect(result.containsPII).toBe(true);
    expect(result.found).toContain(PIIType.SSN);
    expect(result.redacted).toContain('[REDACTED-SSN]');
  });

  it('detects credit card numbers', () => {
    const result = detectPII('Charge card 4111-1111-1111-1111 for $50');
    expect(result.containsPII).toBe(true);
    expect(result.found).toContain(PIIType.CREDIT_CARD);
    expect(result.redacted).toContain('[REDACTED-CC]');
  });

  it('returns containsPII=false on clean text', () => {
    const result = detectPII('This is just normal text with no sensitive data.');
    expect(result.containsPII).toBe(false);
    expect(result.found).toEqual([]);
    expect(result.redacted).toBe('This is just normal text with no sensitive data.');
  });
});

describe('PII redaction in document-shaped payload (PDF/DOCX path)', () => {
  // Mirror the applyRedactionIfApplicable logic for documents.
  function redactDoc(doc: { title: string; sections: Array<{ heading?: string; body: string }> }) {
    const summary: Record<string, number> = {};
    let containsPII = false;
    const newSections = doc.sections.map((s) => {
      const result = detectPII(s.body);
      if (result.containsPII) {
        containsPII = true;
        for (const m of result.matches) summary[m.type] = (summary[m.type] ?? 0) + 1;
        return { ...s, body: result.redacted };
      }
      return s;
    });
    return { redacted: { title: doc.title, sections: newSections }, containsPII, summary };
  }

  it('redacts PII from a document body', () => {
    const original = {
      title: 'Workflow Report',
      sections: [
        { heading: 'Overview', body: 'Generated by alice@example.com on 2026-04-25.' },
        { heading: 'Sensitive', body: 'Customer SSN: 555-12-3456 — flagged for review.' },
        { heading: 'Notes', body: 'No PII here.' },
      ],
    };
    const { redacted, containsPII, summary } = redactDoc(original);
    expect(containsPII).toBe(true);
    expect(redacted.sections[0]!.body).toContain('[REDACTED-EMAIL]');
    expect(redacted.sections[1]!.body).toContain('[REDACTED-SSN]');
    expect(redacted.sections[2]!.body).toBe('No PII here.');
    expect(summary).toMatchObject({ EMAIL: 1, SSN: 1 });
  });

  it('preserves clean documents unchanged', () => {
    const original = {
      title: 'Clean report',
      sections: [{ heading: 'A', body: 'Nothing sensitive.' }, { body: 'More clean text.' }],
    };
    const { redacted, containsPII } = redactDoc(original);
    expect(containsPII).toBe(false);
    expect(redacted).toEqual(original);
  });
});

describe('Real exporter pipeline with redacted document', () => {
  it('produces a valid PDF when redacted bodies contain redaction tokens', async () => {
    const result = await exportPdf(
      {
        title: 'Redacted report',
        sections: [
          { heading: 'PII section', body: 'Email was [REDACTED-EMAIL]; SSN was [REDACTED-SSN].' },
        ],
      },
      { baseName: 'redacted-test' },
    );
    expect(result.bytes.byteLength).toBeGreaterThan(0);
    // PDF magic bytes intact
    const head = Buffer.from(result.bytes.slice(0, 5)).toString('utf8');
    expect(head).toBe('%PDF-');
  }, 15_000);

  it('JSON exporter handles redacted payloads cleanly', () => {
    const result = exportJson(
      { foo: '[REDACTED-EMAIL]', bar: { ssn: '[REDACTED-SSN]', clean: 42 } },
      { baseName: 'redacted-json' },
    );
    expect(result.bytes.byteLength).toBeGreaterThan(0);
    const parsed = JSON.parse(Buffer.from(result.bytes).toString('utf8'));
    expect(parsed.foo).toBe('[REDACTED-EMAIL]');
    expect(parsed.bar.ssn).toBe('[REDACTED-SSN]');
  });
});

describe('Honest gaps documented', () => {
  it('CSV/XLSX redaction is intentionally unsupported in v1.4 — flagged honestly', () => {
    // The export.service.ts applyRedactionIfApplicable returns
    // applied=false for csv/xlsx so the operator sees the gap.
    // This test documents the contract; when cell-level scanning
    // ships, this test should be inverted to verify applied=true.
    const formatsWithoutRedaction = ['csv', 'xlsx'];
    expect(formatsWithoutRedaction).toEqual(['csv', 'xlsx']);
  });
});
