#!/usr/bin/env pwsh
<#
.SYNOPSIS
    JAK Swarm Setup Wizard — Interactive first-run setup.

.DESCRIPTION
    Guides through initial development environment setup:
    1. Check prerequisites (delegates to doctor.ps1)
    2. Install dependencies
    3. Create .env from template
    4. Run database migrations
    5. Seed initial data

.EXAMPLE
    .\scripts\setup.ps1
#>

$ErrorActionPreference = 'Stop'

function Write-Step {
    param([int]$Num, [string]$Title)
    Write-Host ""
    Write-Host "  [$Num] $Title" -ForegroundColor Cyan
    Write-Host "  $('─' * 50)" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "🚀 JAK Swarm Setup Wizard" -ForegroundColor Magenta
Write-Host "   Setting up your development environment..." -ForegroundColor DarkGray

$rootDir = Split-Path $PSScriptRoot -Parent
$swarmDir = Join-Path $rootDir "jak-swarm"

# Attempt to use jak-swarm subfolder, or current directory if structure is flat
if (-not (Test-Path $swarmDir)) {
    $swarmDir = $rootDir
}

# ── Step 1: Prerequisites ────────────────────────────────────────────────────
Write-Step 1 "Checking prerequisites"

$doctorScript = Join-Path $PSScriptRoot "doctor.ps1"
if (Test-Path $doctorScript) {
    & $doctorScript
    # Don't exit on warnings, only hard failures
} else {
    Write-Host "  ⚠️  doctor.ps1 not found — skipping prerequisites check" -ForegroundColor Yellow
}

# ── Step 2: Environment file ─────────────────────────────────────────────────
Write-Step 2 "Environment configuration"

$envFile = Join-Path $swarmDir ".env"
$envExample = Join-Path $swarmDir ".env.example"

if (Test-Path $envFile) {
    Write-Host "  ✅ .env already exists" -ForegroundColor Green
} elseif (Test-Path $envExample) {
    Copy-Item $envExample $envFile
    Write-Host "  ✅ Created .env from .env.example" -ForegroundColor Green
    Write-Host "  ⚠️  Please edit .env and fill in your API keys before starting" -ForegroundColor Yellow
} else {
    # Create minimal .env
    $envContent = @"
# JAK Swarm Environment Configuration
# Generated by setup wizard on $(Get-Date -Format 'yyyy-MM-dd')

# ── Database ──────────────────────────────────────────
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/jak_swarm

# ── LLM Providers (at least one required) ────────────
OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# GEMINI_API_KEY=
# DEEPSEEK_API_KEY=

# ── Auth (Supabase) ──────────────────────────────────
SUPABASE_URL=
SUPABASE_ANON_KEY=
JWT_SECRET=jak-dev-secret-change-in-production

# ── Optional Services ────────────────────────────────
# REDIS_URL=redis://localhost:6379
# E2B_API_KEY=

# ── API Server ────────────────────────────────────────
PORT=3001
NODE_ENV=development
"@
    Set-Content -Path $envFile -Value $envContent -Encoding UTF8
    Write-Host "  ✅ Created .env with defaults" -ForegroundColor Green
    Write-Host "  ⚠️  Please edit .env and add your OPENAI_API_KEY" -ForegroundColor Yellow
}

# ── Step 3: Install dependencies ─────────────────────────────────────────────
Write-Step 3 "Installing dependencies"

Push-Location $swarmDir
try {
    Write-Host "  Running pnpm install..." -ForegroundColor DarkGray
    & pnpm install --frozen-lockfile 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Frozen lockfile failed, trying regular install..." -ForegroundColor Yellow
        & pnpm install 2>&1 | Out-Null
    }
    Write-Host "  ✅ Dependencies installed" -ForegroundColor Green
} catch {
    Write-Host "  ❌ Failed to install dependencies: $_" -ForegroundColor Red
    Write-Host "     Try running manually: cd jak-swarm && pnpm install" -ForegroundColor Cyan
} finally {
    Pop-Location
}

# ── Step 4: Database setup ───────────────────────────────────────────────────
Write-Step 4 "Database setup"

$prismaDir = Join-Path $swarmDir "packages" "db"
if (Test-Path $prismaDir) {
    Push-Location $prismaDir
    try {
        Write-Host "  Running Prisma generate..." -ForegroundColor DarkGray
        & npx prisma generate 2>&1 | Out-Null
        Write-Host "  ✅ Prisma client generated" -ForegroundColor Green

        Write-Host "  Running Prisma migrate..." -ForegroundColor DarkGray
        & npx prisma migrate deploy 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  ✅ Database migrations applied" -ForegroundColor Green
        } else {
            Write-Host "  ⚠️  Migration failed (database might not be running)" -ForegroundColor Yellow
            Write-Host "     Start PostgreSQL, then run: cd packages/db && npx prisma migrate deploy" -ForegroundColor Cyan
        }
    } catch {
        Write-Host "  ⚠️  Database setup skipped: $_" -ForegroundColor Yellow
    } finally {
        Pop-Location
    }
} else {
    Write-Host "  ⚠️  Prisma directory not found" -ForegroundColor Yellow
}

# ── Step 5: Build packages ───────────────────────────────────────────────────
Write-Step 5 "Building packages"

Push-Location $swarmDir
try {
    Write-Host "  Running turbo build..." -ForegroundColor DarkGray
    & npx turbo build 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  ✅ All packages built" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️  Build had issues — check errors manually" -ForegroundColor Yellow
    }
} catch {
    Write-Host "  ⚠️  Build step skipped: $_" -ForegroundColor Yellow
} finally {
    Pop-Location
}

# ── Done ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "─── Setup Complete ───" -ForegroundColor White
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Green
Write-Host "  1. Edit jak-swarm/.env with your API keys" -ForegroundColor DarkGray
Write-Host "  2. Start PostgreSQL (if not running)" -ForegroundColor DarkGray
Write-Host "  3. Run: cd jak-swarm && pnpm dev" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Useful commands:" -ForegroundColor Green
Write-Host "  ./scripts/doctor.ps1     — Diagnose environment issues" -ForegroundColor DarkGray
Write-Host "  pnpm dev                 — Start dev servers" -ForegroundColor DarkGray
Write-Host "  pnpm test                — Run test suite" -ForegroundColor DarkGray
Write-Host ""
