import { Context } from '@temporalio/activity';

export interface GatherMetricsInput { tenantId: string; reportType: string; industry: string }
export interface MetricsData { [key: string]: number | string }
export interface ReportData { title: string; generatedAt: string; metrics: MetricsData; sections: Array<{ name: string; content: string }> }

export async function gatherMetrics(_input: GatherMetricsInput): Promise<MetricsData> {
  Context.current().heartbeat();
  // TODO: query database for tenant KPIs based on _input.industry + _input.reportType
  return { workflowsCompleted: 0, approvalsGranted: 0, agentSteps: 0, avgLatencyMs: 0 };
}

export async function generateReport(input: { tenantId: string; metrics: MetricsData; reportType: string }): Promise<ReportData> {
  // TODO: use DocumentAgent.generate to create a formatted report
  return {
    title: `${input.reportType} Report`,
    generatedAt: new Date().toISOString(),
    metrics: input.metrics,
    sections: [{ name: 'Summary', content: 'Report generated by JAK Swarm.' }],
  };
}

export async function deliverReport(input: { tenantId: string; report: ReportData; deliveryConfig: { email?: string[]; webhook?: string } }): Promise<void> {
  if (input.deliveryConfig.email?.length) {
    // TODO: call EmailAgent with report as attachment
    console.info(`[Temporal] Would deliver report via email to: ${input.deliveryConfig.email.join(', ')}`);
  }
  if (input.deliveryConfig.webhook) {
    // TODO: call WebhookTool with report payload
    console.info(`[Temporal] Would deliver report via webhook to: ${input.deliveryConfig.webhook}`);
  }
}
